version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - demo-service:demo-service
      - resources:resources
    volumes:
      - ./config/dispatcher:/config
  demo-service:
    build: ./demo-service
    environment:
      NODE_ENV: "development"
    links:
      - database:database
    volumes:
      - ./demo-service:/app
  resources:
    image: mu-cl-resources:arm
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
