version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"books\"}, {\"variables\":[],\"name\":\"awards\"}, {\"variables\":[],\"name\":\"clean\"}]"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - demo-service:demo-service
      - resources:resources
    volumes:
      - ./config/dispatcher:/config
  demo-service:
    build: ./demo-service
    environment:
      NODE_ENV: "development"
    links:
      - database:database
    volumes:
      - ./demo-service:/app
  resources:
    image: mu-cl-resources:arm
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      LOG_ACCESS_RIGHTS: "true"
      LOG_OUTGOING_SPARQL_QUERY_RESPONSES: "true"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
  triplestore:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
